export const AUTH_ERRORS = {
	UNAUTHORIZED_USER: "UNAUTHORIZED_USER",
	INVALID_TOKEN: "INVALID_TOKEN",
	MISSING_AUTH_HEADER: "MISSING_AUTH_HEADER",
	ACCESS_DENIED: "ACCESS_DENIED",
	SESSION_EXPIRED: "SESSION_EXPIRED",
	FORBIDDEN_ACTION: "FORBIDDEN_ACTION",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
	ROLE_NOT_ALLOWED: "ROLE_NOT_ALLOWED",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	TOKEN_REQUIRED: "TOKEN_REQUIRED",
};
